- llm4pddl/approaches/base_approach.py
- llm4pddl/approaches/pure_planning_approach.py
- llm4pddl/flags.py
- llm4pddl/main.py
- llm4pddl/structs.py
- llm4pddl/utils.py
- setup.py
- tests/approaches/test_pure_planning_approach.py
- tests/test_main.py
- tests/test_utils.py
note that I also had to make changes to my fork of pyperplan to log these metrics: https://github.com/aibasel/pyperplan/compare/master...tomsilver:pyperplan:master
I also added a random seed here and randomized tiebreaking in search.
> refactor metrics to be problem-specific and add node metrics for planning approaches

- scripts/kill_openstack.py
> script to kill all openstack experiments

- llm4pddl/utils.py
> add fd with hff and gbfs

- scripts/launch_local.py
- scripts/launch_openstack.py
> launch experiments in sequence on one openstack machine

- README.md
When I save the readme it for some reason added a bunch of spaces so it looks like i made more changes than I did.
> Tranformers install note

- .github/workflows/llm4pddl.yml
- README.md
- llm4pddl/llm_interface.py
- llm4pddl/main.py
- llm4pddl/utils.py
- mypy.ini
- scripts/cluster_utils.py
> switch hashing scheme for llm cache filenames

- llm4pddl/approaches/llm_open_loop_approach.py
- llm4pddl/flags.py
- llm4pddl/utils.py
- tests/approaches/test_llm_open_loop_approach.py
- tests/approaches/test_llm_planning_approach.py
implementing an idea by @reeceshuttle to reduce token counts
> group-by-predicate prompting method

- llm4pddl/approaches/llm_open_loop_approach.py
- llm4pddl/approaches/llm_planning_approach.py
- llm4pddl/flags.py
- llm4pddl/utils.py
- tests/approaches/test_llm_open_loop_approach.py
- tests/approaches/test_llm_planning_approach.py
see also changes in pyperplan: https://github.com/tomsilver/pyperplan/compare/aibasel:pyperplan:master...master
>  option to use partial plans as heuristic guidance instead of initializing the queue

- llm4pddl/approaches/llm_open_loop_approach.py
- llm4pddl/approaches/llm_planning_approach.py
- llm4pddl/llm_interface.py
- llm4pddl/utils.py
I verified that the performance of gripper and movie is still good after this change. also, the querying time seems much faster now!
> add stop token

- llm4pddl/approaches/llm_open_loop_approach.py
- llm4pddl/llm_interface.py
- llm4pddl/main.py
- llm4pddl/utils.py
per @reeceshuttle , this will have a lower token cost, and also may better tap into the pretraining of the LLM
> change stop token to qa pattern

- llm4pddl/approaches/llm_open_loop_approach.py
- llm4pddl/utils.py
- tests/test_utils.py
Just ignore the name of this branch. It doesn't read the cache files. I've tweaked the prompt format so that a colon is added after the Q and A's and ensured that a tiny bit of structure is allowed for the examples inside of the minify_pddl_problem() function. This will be minor, since it will be two ':' tokens and 4 '\n' tokens for each example.
> changes to prompt structure

- llm4pddl/envs/pyperplan_env.py
this will assure that we always are prompting/training on the shortest tasks (shortest in terms of string length). it looks like there a number of changes, but many of the domains seem to roughly correspond to the original order.
> sort pyperplan benchmark tasks by string length

- llm4pddl/main.py
- llm4pddl/structs.py
- tests/test_main.py
a small change that will make dataset saving and loading a little easier
> change the way that task IDs are created

- llm4pddl/dataset.py
- llm4pddl/flags.py
- llm4pddl/main.py
- tests/approaches/test_llm_open_loop_approach.py
- tests/approaches/test_llm_planning_approach.py
- tests/test_main.py
closes #62
usage example:
```
python llm4pddl/main.py --env pyperplan-blocks --approach llm-standard --seed 0 --load_data --debug
```
> data saving and loading

- llm4pddl/approaches/llm_open_loop_approach.py
> include constants in prompting

- scripts/analyze_results.py
closes #69 
example command: ```python scripts/analyze_results.py --a_dir ~/Dropbox/llm4pddl/results/aug14/results --b_dir ~/Dropbox/llm4pddl/results/aug22/results```
example output (don't worry about the output itself):
```
Git commit hashes seen in /Users/tom/Dropbox/llm4pddl/results/aug14/results/:
b4075fdb5a3ef16e938d3443e184a64455bb204a
d4ea4571087df9d1c1f3a1aed053e3e82093683f
Git commit hashes seen in /Users/tom/Dropbox/llm4pddl/results/aug22/results/:
59d8a1a0dfef8f7bb84b5528b1cb1c7624da457c
#################### SAME IN BOTH: ###################
env      approach             experiment_id  solve_time  nodes_created  nodes_expanded  success VERSION
0       pyperplan-airport  llm-standard      airport-llm-standard    6.124642            NaN             NaN      0.0       A
1 …
```
> add AB testing functionality to analysis script

- llm4pddl/utils.py
- tests/test_utils.py
removes a little redundant code and makes way for a future PR
> minor refactoring of the task loading utilities

- llm4pddl/envs/custom_env.py
- llm4pddl/envs/pyperplan_env.py
- llm4pddl/envs/single_dir_env.py
- llm4pddl/utils.py
continuing to reduce redundant code and make way for future PRs related to data augmentation
> larger refactor of pyperplan and custom envs

- llm4pddl/structs.py
- tests/test_utils.py
> add problem_str and domain_str to Task

- llm4pddl/utils.py
- tests/test_utils.py
> pyperplan problem to string

- llm4pddl/utils.py
- tests/envs/test_custom_env.py
- tests/test_utils.py
> remove unneeded get_benchmark_task utilities

- llm4pddl/envs/assets/pddl/augmented/generate_augmented_tasks.py
> data augmentation: only keep tasks whose plans use all the operators

- scripts/configs/augment.yaml
- scripts/configs/main.yaml
> remove envs with preprocessed domains

- llm4pddl/envs/assets/pddl/augmented/generate_augmented_tasks.py
the issue was that two problems were identical except for the meaningless problem name
> fixing the identification of unique tasks in data augmentation

- llm4pddl/envs/multi_dir_env.py
- llm4pddl/envs/single_dir_env.py
- llm4pddl/flags.py
- tests/approaches/test_llm_open_loop_approach.py
- tests/approaches/test_llm_planning_approach.py
- tests/approaches/test_pure_planning_approach.py
- tests/envs/test_augmented_env.py
- tests/envs/test_custom_env.py
- tests/envs/test_envs.py
- tests/envs/test_pyperplan_env.py
- tests/test_main.py
> add optional train task offset

- scripts/analyze_results.py
also add "approach_id" as a unique approach identifier
> make analysis table multicolumn

- run_autoformat.sh
@reeceshuttle @Alchemy5 this should fix the autoformatting issues that you've both encountered
> add setup.py to autoformatting list

- llm4pddl/utils.py
> switch parenthesis format in `pred_to_str`

- llm4pddl/flags.py
- llm4pddl/utils.py
> include grounding in timeout

- scripts/analyze_results.py
> fix analyze results script in case without experiment id

- llm4pddl/flags.py
- scripts/analyze_results.py
- tests/approaches/test_llm_planning_approach.py
> make an option to continue or break when a bad action is hit

- .github/workflows/llm4pddl.yml
- README.md
- llm4pddl/flags.py
- scripts/cluster_utils.py
- scripts/configs/main.yaml
also:
* makes FLAGS optional in config files and adds optional ARGS for envs and approaches
* changes `llm_autoregressive_prompting` action so that we can do `no-llm_autoregressive_prompting` to disable it. and now the default is to do autoregressive prompting
* push minimum python version to 3.9
> main config updates

- llm4pddl/approaches/llm_open_loop_approach.py
- llm4pddl/approaches/random_actions_approach.py
- llm4pddl/utils.py
- tests/approaches/test_llm_open_loop_approach.py
- tests/approaches/test_llm_planning_approach.py
- tests/approaches/test_random_actions_approach.py
- tests/test_llm_interface.py
a baseline that uses random partial plans instead of the LLM output. useful with llm-standard/multi-plan
> random plan guidance

- .github/workflows/llm4pddl.yml
- README.md
- llm4pddl/flags.py
- scripts/configs/main.yaml
I forgot that the cluster has 3.8
> revert minimum python version to 3.8

- llm4pddl/approaches/llm_open_loop_approach.py
- scripts/configs/main.yaml
> fix autoregress + random
